export const lasagnaMock = {
  meals: [
    {
      idMeal: '52844',
      strMeal: 'Lasagne',
      strDrinkAlternate: null,
      strCategory: 'Pasta',
      strArea: 'Italian',
      strInstructions:
        'Heat the oil in a large saucepan.',
      strMealThumb:
        'https://www.themealdb.com/images/media/meals/wtsvxx1511296896.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=gfhfsBPt46s',
      strIngredient1: 'Olive Oil',
      strIngredient2: 'Bacon',
      strIngredient3: 'Onion',
      strIngredient4: 'Celery',
      strIngredient5: 'Carrots',
      strIngredient6: 'Garlic',
      strIngredient7: 'Minced Beef',
      strIngredient8: 'Tomato Puree',
      strIngredient9: 'Chopped Tomatoes',
      strIngredient10: 'Honey',
      strIngredient11: 'Lasagne Sheets',
      strIngredient12: 'Creme Fraiche',
      strIngredient13: 'Mozzarella Balls',
      strIngredient14: 'Parmesan Cheese',
      strIngredient15: 'Basil Leaves',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1 tblsp ',
      strMeasure2: '2',
      strMeasure3: '1 finely chopped ',
      strMeasure4: '1 Stick',
      strMeasure5: '1 medium',
      strMeasure6: '2 cloves chopped',
      strMeasure7: '500g',
      strMeasure8: '1 tbls',
      strMeasure9: '800g',
      strMeasure10: '1 tblsp ',
      strMeasure11: '500g',
      strMeasure12: '400ml',
      strMeasure13: '125g',
      strMeasure14: '50g',
      strMeasure15: 'Topping',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'https://www.bbcgoodfood.com/recipes/classic-lasagne',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
  ],
};

export const ABCMock = {
  drinks: [
    {
      idDrink: '13501',
      strDrink: 'ABC',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Shot',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Shot glass',
      strInstructions: 'Layered in a shot glass.',
      strInstructionsES:
        'Coloque todos los ingredientes en un vaso de chupito.',
      strInstructionsDE: 'Schichtaufbau in einem Schnapsglas.',
      strInstructionsFR: null,
      strInstructionsIT:
        'Versa in ordine di lettera i vari ingredienti.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb:
        'https://www.thecocktaildb.com/images/media/drink/tqpvqp1472668328.jpg',
      strIngredient1: 'Amaretto',
      strIngredient2: 'Baileys irish cream',
      strIngredient3: 'Cognac',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1/3 ',
      strMeasure2: '1/3 ',
      strMeasure3: '1/3 ',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2016-08-31 19:32:08',
    },
  ],
};
