// DRINKS API MOCK https://www.thecocktaildb.com/api.php

export const wineIngredientMock = {
  drinks: [
    {
      strDrink: 'Archbishop',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/4g6xds1582579703.jpg',
      idDrink: '11052',
    },
    {
      strDrink: 'Berry Deadly',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/zk74k21593351065.jpg',
      idDrink: '12876',
    },
    {
      strDrink: 'Clove Cocktail',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/qxvtst1461867579.jpg',
      idDrink: '11255',
    },
    {
      strDrink: 'Thriller',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/rvuswq1461867714.jpg',
      idDrink: '12388',
    },
    {
      strDrink: 'Whisky Mac',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/yvvwys1461867858.jpg',
      idDrink: '12518',
    },
  ],
};

export const orangeadeDrinksMock = {
  drinks: [
    {
      idDrink: '12618',
      strDrink: 'Orangeade',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Cocktail',
      strIBA: null,
      strAlcoholic: 'Non alcoholic',
      strGlass: 'Highball glass',
      strInstructions: 'Place some ice cubes in a large tumbler or highball glass [...]',
      strInstructionsES: null,
      strInstructionsDE: 'Legen Sie einige Eiswürfel in einen großen Becher oder [...]',
      strInstructionsFR: null,
      strInstructionsIT: 'Mettere alcuni cubetti di ghiaccio in un [...]',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/ytsxxw1441167732.jpg',
      strIngredient1: 'Lemon juice',
      strIngredient2: 'Orange juice',
      strIngredient3: 'Sugar syrup',
      strIngredient4: 'Soda water',
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '5 cl ',
      strMeasure2: '15 cl ',
      strMeasure3: '2-3 cl ',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2015-09-02 05:22:12',
    },
    { mock: 'mock' },
  ],
};

export const letterYDrinksMock = {
  drinks: [
    {
      idDrink: '17219',
      strDrink: 'Yellow Bird',
      strDrinkAlternate: null,
      strTags: 'IBA,NewEra',
      strVideo: null,
      strCategory: 'Cocktail',
      strIBA: 'New Era Drinks',
      strAlcoholic: 'Alcoholic',
      strGlass: 'Cocktail glass',
      strInstructions: 'Shake and strain into a chilled cocktail glass',
      strInstructionsES: null,
      strInstructionsDE: 'In ein gekühltes Cocktailglas schütteln und abseihen.',
      strInstructionsFR: null,
      strInstructionsIT: 'Shakerare e filtrare in una coppetta da cocktail ghiacciata',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/2t9r6w1504374811.jpg',
      strIngredient1: 'White Rum',
      strIngredient2: 'Galliano',
      strIngredient3: 'Triple Sec',
      strIngredient4: 'Lime Juice',
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '3 cl',
      strMeasure2: '1.5 cl',
      strMeasure3: '1.5 cl',
      strMeasure4: '1.5 cl',
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-09-02 18:53:31',
    },
    {
      idDrink: '12728',
      strDrink: 'Yoghurt Cooler',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Other/Unknown',
      strIBA: null,
      strAlcoholic: 'Non alcoholic',
      strGlass: 'Highball Glass',
      strInstructions: 'Place all ingredients in the blender jar [...]',
      strInstructionsES: null,
      strInstructionsDE: 'Alle Zutaten in den Mixer geben [...]',
      strInstructionsFR: null,
      strInstructionsIT: 'Mettere tutti gli ingredienti [...]',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/trttrv1441254466.jpg',
      strIngredient1: 'Yoghurt',
      strIngredient2: 'Fruit',
      strIngredient3: 'Ice',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 cup ',
      strMeasure2: '1 cup ',
      strMeasure3: null,
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2015-09-03 05:27:46',
    },
  ],
};
