export const avocadoIngredientsMock = {
  meals: [
    {
      strMeal: 'Cajun spiced fish tacos',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/uvuyxu1503067369.jpg',
      idMeal: '52819',
    },
    {
      strMeal: 'Chickpea Fajitas',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/tvtxpq1511464705.jpg',
      idMeal: '52870',
    },
    {
      strMeal: 'Chocolate Avocado Mousse',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/uttuxy1511382180.jpg',
      idMeal: '52853',
    },
    {
      strMeal: 'Crock Pot Chicken Baked Tacos',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/ypxvwv1505333929.jpg',
      idMeal: '52830',
    },
    {
      strMeal: 'Salmon Avocado Salad',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/1549542994.jpg',
      idMeal: '52960',
    },
  ],
};

export const avocadoRecipesMock = {
  meals: [
    {
      idMeal: '52960',
      strMeal: 'Salmon Avocado Salad',
      strDrinkAlternate: null,
      strCategory: 'Seafood',
      strArea: 'British',
      strInstructions: 'Season the salmon, then rub with oil.[...]',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/1549542994.jpg',
      strTags: 'Paleo,Keto,LowCarbs,Salad,Alcoholic,Halloween,',
      strYoutube: 'https://www.youtube.com/watch?v=FJiu2S0Xap0',
      strIngredient1: 'Salmon',
      strIngredient2: 'Avocado',
      strIngredient3: 'Cucumber',
      strIngredient4: 'Spinach',
      strIngredient5: 'Mint',
      strIngredient6: 'Lime',
      strIngredient7: 'Honey',
      strIngredient8: 'Olive Oil',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '400g',
      strMeasure2: '3',
      strMeasure3: '1',
      strMeasure4: '400g',
      strMeasure5: '4 tbs',
      strMeasure6: 'zest and juice of 1',
      strMeasure7: '2 tsp',
      strMeasure8: '3 tbs',
      strMeasure9: '',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'https://www.bbcgoodfood.com/recipes/4521/salmon-avocado-and-cucumber-salad',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52853',
      strMeal: 'Chocolate Avocado Mousse',
      strDrinkAlternate: null,
      strCategory: 'Dessert',
      strArea: 'British',
      strInstructions: '1. Blend all the mousse ingredients together in your food[...]',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/uttuxy1511382180.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=wuZffe60q4M',
      strIngredient1: 'Banana',
      strIngredient2: 'Cacao',
      strIngredient3: 'Avocado',
      strIngredient4: 'Honey',
      strIngredient5: 'Lemon Juice',
      strIngredient6: 'Vanilla',
      strIngredient7: 'Water',
      strIngredient8: 'Sea Salt',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1',
      strMeasure2: '3 tbsp',
      strMeasure3: '1',
      strMeasure4: '2 tblsp ',
      strMeasure5: '1 tsp ',
      strMeasure6: '1 tsp ',
      strMeasure7: '2 tbsp',
      strMeasure8: 'pinch',
      strMeasure9: '',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'http://www.hemsleyandhemsley.com/recipe/chocolate-avocado-mousse/',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
  ],
};

export const letterYMock = {
  meals: [
    {
      idMeal: '52871',
      strMeal: 'Yaki Udon',
      strDrinkAlternate: null,
      strCategory: 'Vegetarian',
      strArea: 'Japanese',
      strInstructions: 'Boil some water in a large saucepan. [...]',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/wrustq1511475474.jpg',
      strTags: 'LowCalorie',
      strYoutube: 'https://www.youtube.com/watch?v=5Iy0MCowSvA',
      strIngredient1: 'Udon Noodles',
      strIngredient2: 'Sesame Seed Oil',
      strIngredient3: 'Onion',
      strIngredient4: 'Cabbage',
      strIngredient5: 'Shiitake Mushrooms',
      strIngredient6: 'Spring Onions',
      strIngredient7: 'Mirin',
      strIngredient8: 'Soy Sauce',
      strIngredient9: 'Caster Sugar',
      strIngredient10: 'Worcestershire Sauce',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '250g',
      strMeasure2: '2 tbs',
      strMeasure3: '1 sliced',
      strMeasure4: '0.25',
      strMeasure5: '10',
      strMeasure6: '4',
      strMeasure7: '4 tbsp',
      strMeasure8: '2 tbs',
      strMeasure9: '1 tblsp ',
      strMeasure10: '1 tblsp ',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'https://www.bbcgoodfood.com/recipes/yaki-udon',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
  ],
};
